#!/usr/bin/env node
/**
 * PostToolUse hook: format the file Claude just edited.
 * Generated by aia-harness — language-aware. Never blocks.
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { readStdinRaw, parseHookEvent } from "./hook-io.mjs";

const event = parseHookEvent(readStdinRaw());
if (!event) process.exit(0);

const file = event && event.tool_input && (event.tool_input.file_path || event.tool_input.path);
if (!file || typeof file !== "string") process.exit(0);

const projectDir = process.env.CLAUDE_PROJECT_DIR || process.cwd();
const ext = path.extname(file).toLowerCase();

function localBin(name) {
  var p = path.join(projectDir, "node_modules", ".bin", name);
  return fs.existsSync(p) ? p : null;
}

try {
  if ([".js",".jsx",".ts",".tsx",".mjs",".cjs",".mts",".cts",".json",".jsonc",".css",".scss",".sass",".less",".md",".mdx",".html",".htm",".yaml",".yml",".vue",".svelte",".astro"].includes(ext)) {
    var biome = localBin("biome");
    var prettier = localBin("prettier");
    if (biome) execFileSync(biome, ["format", "--write", file], { stdio: "ignore" });
    else if (prettier) execFileSync(prettier, ["--write", file], { stdio: "ignore" });
  }
} catch {
  // Formatting is best-effort; never block the edit.
}

process.exit(0);
