#!/usr/bin/env node
// Generated by aia-harness — install the suggested Claude Code plugins.
// Plugins install at USER level (Claude Code has no per-project plugin install).
// Run with -y to skip the confirmation prompt.
import { spawnSync } from "node:child_process";
import * as rl from "node:readline/promises";

const check = spawnSync("claude", ["--version"], { stdio: "ignore", shell: true, windowsHide: true });
if (check.status !== 0) {
  process.stderr.write("aia-harness: 'claude' CLI not found — install Claude Code first.\n");
  process.exit(1);
}

const marketplaces = [
  [
    "claude-plugins-official",
    "anthropics/claude-plugins-official"
  ],
  [
    "ui-ux-pro-max-skill",
    "nextlevelbuilder/ui-ux-pro-max-skill"
  ]
];
const plugins = [
  {
    "name": "claude-code-setup",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "claude-md-management",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "superpowers",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "ui-ux-pro-max",
    "marketplace": "ui-ux-pro-max-skill"
  },
  {
    "name": "context7",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "github",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "hookify",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "code-review",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "pr-review-toolkit",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "security-guidance",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "commit-commands",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "feature-dev",
    "marketplace": "claude-plugins-official"
  },
  {
    "name": "frontend-design",
    "marketplace": "claude-plugins-official"
  }
];

if (!process.argv.includes("-y")) {
  const iface = rl.createInterface({ input: process.stdin, output: process.stdout });
  const ans = await iface.question(
    `About to add ${marketplaces.length} marketplace(s) and install ${plugins.length} plugin(s):
  - claude-code-setup [development] Setup helpers incl. the claude-automation-recommender used by /aia-harness:init.
  - claude-md-management [development] CLAUDE.md audit/improve + revise-claude-md (claude-md-improver, revise-claude-md skills).
  - superpowers [workflow] Core skills library: TDD, systematic-debugging, brainstorming, planning, worktrees, collaboration patterns.
  - ui-ux-pro-max [workflow] UI/UX design intelligence: 67 styles, 96 palettes, 57 font pairings, 25 charts, 13 stack guidelines (nextlevelbuilder).
  - context7 [search] Up-to-date library/framework docs (plugin form).
  - github [workflow] GitHub issues / PRs / releases integration.
  - hookify [quality] Create hooks from conversation patterns to prevent repeat mistakes.
  - code-review [quality] Structured pull-request / diff review.
  - pr-review-toolkit [quality] Deeper PR review workflow.
  - security-guidance [quality] Security best-practice guidance and review.
  - commit-commands [workflow] Commit / push / open-PR helper commands.
  - feature-dev [workflow] Guided feature development with codebase understanding.
  - frontend-design [workflow] Distinctive, production-grade frontend implementation (Anthropic).
Proceed? [y/N] `
  );
  iface.close();
  if (!ans.match(/^y$/i)) { console.log("Aborted."); process.exit(0); }
}

for (const [, repo] of marketplaces) {
  spawnSync("claude", ["plugin", "marketplace", "add", repo], { stdio: "inherit", shell: true, windowsHide: true });
}
for (const p of plugins) {
  spawnSync("claude", ["plugin", "install", p.name + "@" + p.marketplace], { stdio: "inherit", shell: true, windowsHide: true });
}
console.log("Done. Restart Claude Code to load the new plugins.");
